spring:
  datasource:
    url: "${DATABASE_URL}"
    username: "${DATABASE_USERNAME}"
    password: "${DATABASE_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.lab.non_contextual_creation: true
      hibernate.transaction.jta.platform: null
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/migration/dev
server:
  port: 8080
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: "${JWT_SECRET}"