CREATE TABLE IF NOT EXISTS doctors (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    crm VARCHAR(6) NOT NULL UNIQUE,
    specialty VARCHAR(100) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    street VARCHAR(100) NOT NULL,
    postal_code CHAR(9) NOT NULL,
    complement VARCHAR(100),
    city VARCHAR(100) NOT NULL,
    state CHAR(2) NOT NULL,
    number VARCHAR(20)
);